name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build_ui:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build
        working-directory: ./amethyst.ui
        run: |
          npm ci
          npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ui-build
          path: ./dist/**

  build_api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      working-directory: ./amethyst
      run: dotnet restore
    - name: Test
      working-directory: ./amethyst.tests
      run: dotnet test
    - name: Build win-x64
      working-directory: ./amethyst
      run: dotnet publish ./amethyst.csproj /p:PublishProfile=./Properties/PublishProfiles/WinX64.pubxml
    - name: Build linux-x64
      working-directory: ./amethyst
      run: dotnet publish ./amethyst.csproj /p:PublishProfile=./Properties/PublishProfiles/LinuxX64.pubxml
    - name: Build linux-arm
      working-directory: ./amethyst
      run: dotnet publish ./amethyst.csproj /p:PublishProfile=./Properties/PublishProfiles/LinuxArm.pubxml
    - name: Build linux-arm64
      working-directory: ./amethyst
      run: dotnet publish ./amethyst.csproj /p:PublishProfile=./Properties/PublishProfiles/LinuxArm64.pubxml
    - name: Build osx-x64
      working-directory: ./amethyst
      run: dotnet publish ./amethyst.csproj /p:PublishProfile=./Properties/PublishProfiles/OsxX64.pubxml

