name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Restore UI
      working-directory: ./jamster.ui
      run: npm ci

    - name: Lint UI
      working-directory: ./jamster.ui
      run: npm run lint

    - name: Build UI
      working-directory: ./jamster.ui
      run: npm run build

    - name: Restore API
      working-directory: ./jamster.engine
      run: dotnet restore
      
    - name: Test API
      working-directory: ./jamster.engine.tests
      run: dotnet test
      
    - name: Build win-x64
      working-directory: ./jamster.engine
      run: dotnet publish ./jamster.csproj /p:PublishProfile=./Properties/PublishProfiles/WinX64.pubxml

    - name: Build linux-x64
      working-directory: ./jamster.engine
      run: dotnet publish ./jamster.csproj /p:PublishProfile=./Properties/PublishProfiles/LinuxX64.pubxml
      
    - name: Build linux-arm64
      working-directory: ./jamster.engine
      run: dotnet publish ./jamster.csproj /p:PublishProfile=./Properties/PublishProfiles/LinuxArm64.pubxml

    - name: Prepare output
      shell: bash
      run: |
        mkdir ./output
        mkdir ./output/bin
        mkdir ./output/bin/win-x64
        mkdir ./output/bin/linux-x64
        mkdir ./output/bin/linux-arm64
        mv ./jamster.engine/bin/Release/net8.0/win-x64/publish/** ./output/bin/win-x64/
        mv ./jamster.engine/bin/Release/net8.0/linux-x64/publish/** ./output/bin/linux-x64/
        mv ./jamster.engine/bin/Release/net8.0/linux-arm64/publish/** ./output/bin/linux-arm64/
        cp -r ./output/bin/win-x64/wwwroot ./output/wwwroot
        rm -r ./output/bin/win-x64/wwwroot
        rm -r ./output/bin/linux-x64/wwwroot
        rm -r ./output/bin/linux-arm64/wwwroot
        cp ./start.cmd ./output/
        chmod +x ./output/start.cmd

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./output/**
        retention-days: 1
        compression-level: 9
